### ISSUE TITLE
Installation of ghdl package fails

### ISSUE THREAD

**Issue by popas90** [travis-ci/apt-package-whitelist#2696]
I'm using this in my travis.yml file:
```
addons:
  apt:
    packages:
    - ghdl
```

But the installation fails, although ghdl is on the whitelist:
`Package 'ghdl' has no installation candidate`

More details in this log:
https://travis-ci.org/popas90/FANN_vhd/builds/115410612
