### ISSUE TITLE
APT whitelist request for libxxf86vm-dev

### ISSUE THREAD

**Issue by PiotrJustyna** [travis-ci/apt-package-whitelist#2721]
Even though libxxf86vm-dev and its various flavors:

- libxxf86vm-dev
- libxxf86vm-dev:i386
- libxxf86vm1
- libxxf86vm1:i386

are whitelisted, my Travis builds break with the following message:

```[31;1mDisallowing packages: libXxf86vm-dev [0m
If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process```.

I have also tried ```libxxf86vm1``` but it fails with the same error.

Am I doing something wrong?

**Comment by PiotrJustyna** [comment]
Interesting observation. The package does seem to work, but only in certain configurations and depending where it's installed from. Example:

* Working, but a bit hacky solution:
```
cache:
  directories:
  - $HOME/.stack

matrix:
    include:
        - env: CABALVER=1.22 GHCVER=7.10.3
          addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.3, freeglut3-dev], sources: [hvr-ghc]}}

before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - sudo add-apt-repository ppa:team-xbmc/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install libXxf86vm-dev
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
    - stack setup

script:
    - stack build
    - stack test
```

* Not working, but a bit cleaner solution:
```
sudo: false

cache:
  directories:
  - $HOME/.stack

matrix:
    include:
        - env: CABALVER=1.22 GHCVER=7.10.3
          addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.3, freeglut3-dev, libXxf86vm-dev], sources: [hvr-ghc]}}

before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
    - stack setup

script:
    - stack build
    - stack test
```

If the solution is satisfactory for the users, the defect can be closed.
