### ISSUE TITLE
Listed packages can not be installed in Precise

### ISSUE THREAD

**Issue by Paebbels** [travis-ci/apt-package-whitelist#2979]
Hello,

according to your package list for Ubuntu Precise, the following packages are available:

  - python3.5
  - gnat-5

My Travis-CI run [reports](https://travis-ci.org/VLSI-EDA/PoC/jobs/128990237#L148), that both can not be found.

> Unable to locate package python3.5
> ...
> Unable to locate package gnat-5

The [`.travis.yml`](https://github.com/VLSI-EDA/PoC/commit/3489c194bf5a81c052cc850b119b52cdf0a43ab0) looks as follows:

```yml
language: python
matrix:
  include:
    - os: linux
      env: CONFIG="Trusty,Python3.5,libgnat-4.8,grc-1.9"
      sudo: required
      dist: trusty
      python: "3.5"
      before_install:
        - sudo apt-get install -y libgnat-4.8
        - sudo ./tools/Travis-CI/grc.setup.sh
      install:
        - pip3 install -r tools/Travis-CI/requirements.txt
      before_script:
        - ./tools/Travis-CI/ghdl.setup.sh
        - ./tools/Travis-CI/poc.setup.sh
      script:
        - ./tools/Travis-CI/poc.run.sh
    - os: linux
      env: CONFIG="Precise,Python3.5,gnat-5"
      addons:
        apt:
          packages:
            - python3.5
            - gnat-5
      install:
        - pip3 install -r tools/Travis-CI/requirements.txt
      before_script:
        - ./tools/Travis-CI/ghdl.setup.sh
        - ./tools/Travis-CI/poc.setup.sh
      script:
        - ./tools/Travis-CI/poc.run.sh
```

I also tried to set `python: "3.5"` in my second matrix configuration, which causes this [message](https://travis-ci.org/VLSI-EDA/PoC/jobs/128992137#L107):

> 3.5 is not installed; attempting download

This message in strange in 2 ways:

 1. Why does it start with "3.5" and does not name Python
 2. No download attempt is made....
