### ISSUE TITLE
Can't install siversearcher-ag from debian-sid source

### ISSUE THREAD

**Issue by DamienCassou** [travis-ci/apt-package-whitelist#4086]
My `.travis.yml` file contains:

```yml
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - silversearcher-ag
```

[This results](https://travis-ci.org/DamienCassou/klassified.el/builds/222496286) in:

```
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install silversearcher-ag" failed and exited with 100 during .
```

Can that be related to an earlier warning:

```
W: There is no public key available for the following key IDs:

7638D0442B90D010
```

?
