### ISSUE TITLE
APT whitelist request for gcc-8 in TRUSTY

### ISSUE THREAD

**Issue by grooverdan** [travis-ci/apt-package-whitelist#4283]

**Comment by travisbot** [comment]
***This is an automated comment.***

Ran tests, but could not found source package. Either the source package for gcc-8 does not exist, or the package needs an APT source. If you wish to add an APT source, please follow the directions on https://github.com/travis-ci/apt-source-whitelist#source-approval-process. Build results: https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/376205443.

**Comment by tanzislam** [comment]
I do it like:

```yml
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
        - gcc-8
        # ... etc. ...
```
