### ISSUE TITLE
APT whitelist request for xmlstarlet

### ISSUE THREAD

**Issue by gschueler** [travis-ci/apt-package-whitelist#740]
http://packages.ubuntu.com/precise/xmlstarlet

**Comment by romani** [comment]
in my build https://travis-ci.org/checkstyle/checkstyle/jobs/182711210#L184 `xmlstarlet: command not found` 
am I miss smth ?

**Comment by romani** [comment]
Looks like solution is : 
```
sudo: false
cache:
  apt: true
  directories:
    - ~/.m2/

addons:
  apt:
    packages:
      - xsltproc
      - xmlstarlet

```
